using O2DESNet;

namespace SimulationChallenge2026;

/// <summary>
/// Abstract base class for source generation in DES.
///
/// A generator acts as a source node in the process flow.
/// When a load is generated by the generator, the inheriting class
/// defines the generation logic and may forward the load to downstream activities.
///
/// Subclasses must implement:
/// - Generate(TLoad): defines the generation logic
/// </summary>
public abstract class Generator<TLoad> : Sandbox
{
    public bool EnableLog { get; set; } = true;

    /// <summary>
    /// Event triggered when a load arrives at the generator output
    /// and is ready to be forwarded downstream.
    /// </summary>
    public List<Action<TLoad>> OnArrive { get; } = new();

    protected Generator(string id, int seed = 0)
        : base(id: id, seed: seed)
    {
    }

    /// <summary>
    /// Raise the arrival event for a generated load.
    /// </summary>
    protected void Arrive(TLoad load)
    {
        Log("Generate", load);

        foreach (var action in OnArrive)
            action?.Invoke(load);
    }

    /// <summary>
    /// Connect this generator to the next activity in the process flow.
    ///
    /// Flow semantics:
    /// 1. When a load ARRIVES from this generator,
    ///    it REQUESTS START in the next activity.
    ///
    /// Optional:
    /// - filter:
    ///   Controls whether an arriving load should be forwarded
    ///   to the next activity. This is useful for routing logic,
    ///   such as port-based, route-based, or type-based transitions.
    /// </summary>
    public void ConnectTo(
        ActivityHandler<TLoad> next,
        Func<TLoad, bool>? filter = null)
    {
        if (next == null)
            throw new ArgumentNullException(nameof(next));

        // ============================================================
        // Forward flow: Arrive -> next.RequestStart
        // ============================================================
        this.OnArrive.Add(load =>
        {
            // Forward the arriving load to the next activity only
            // if it satisfies the optional filter condition.
            if (filter == null || filter(load))
            {
                next.RequestStart(load);
            }
        });
    }

    protected void Log(string eventName, object? load = null)
    {
        if (!EnableLog) return;

        var time = $"[{ClockTime:d\\.hh\\:mm\\:ss}]";

        if (load == null)
            Console.WriteLine($"{time} {Id} | {eventName}");
        else
            Console.WriteLine($"{time} {Id} | {eventName} | {load}");
    }
}